filebeat.inputs:
- type: filestream
  enabled: true
  parsers:
    - multiline:
        type: pattern
        pattern: '^[[:space:]]Event:'
        negate: false
        match: after
  include_lines: ['Event:']
  paths:
   - IS_HOME/repository/logs/wso2carbon.log
filebeat.registry.path: /var/lib/filebeat/registry
output.logstash:
  hosts: ["localhost:5044"]

